GOOSE_PROVIDER: ollama
GOOSE_MODEL: qwen2.5-7b-instruct-1m
extensions:
  computercontroller:
    enabled: false
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  memory:
    enabled: true
    name: memory
    type: builtin
